- name: start broker
  shell: ./kafka-start.sh
  args:
    chdir: "{{ confluent_bin_dir }}"
  register: broker_status

- name: stop broker
  shell: ./kafka-stop.sh
  args:
    chdir: "{{ confluent_bin_dir }}"
  register: broker_status

- name: restart broker
  shell: ./kafka-restart.sh
  args:
    chdir: "{{ confluent_bin_dir }}"