- hosts: preflight
  gather_facts: yes
  vars:
    ansible_user: rioadmin
  tasks:
  - import_role:
      name: confluent.common
    tags:
      - common

- hosts: preflight
  vars:
    ansible_user: rioadmin
  tasks:
  - import_role:
      name: confluent.preflight
    tags:
      - install
      
- hosts: zookeeper
  vars:
  roles:
      - { role: confluent.zookeeper, tags: zookeeper }
      
- hosts: broker
  roles:
      - { role: confluent.kafka-broker, tags: broker }

- hosts: schema-registry
  tasks:
  - import_role:
      name: confluent.schema-registry

- hosts: connect-distributed
  tasks:
  - import_role:
      name: confluent.connect-distributed
- hosts: ksql
  tasks:
  - import_role:
      name: confluent.ksql
- hosts: control-center
  tasks:
  - import_role:
      name: confluent.control-center
- hosts: kafka-rest
  tasks:
  - import_role:
      name: confluent.kafka-rest
- hosts: tools
  tasks:
  - import_role:
      name: confluent.tools
    tags:
      - post-install
