- name: copy local server truststore to server
  copy: 
    src: ./kafka-server.truststore.jks
    dest: "{{confluent_home }}/var/ssl/"

- name: copy local client truststore to server
  copy: 
    src: ./kafka-client.truststore.jks 
    dest: "{{confluent_home }}/var/ssl/"

- name: import CARoot to client truststore
  shell: /opt/confluent/bin/trust.sh >> trust.log
  args:
    chdir: "{{confluent_home }}/var/ssl/"
    creates: trust.log

- name: fetch server truststore to local machine
  fetch: 
    src: "{{ truststore_path }}"
    dest: kafka-server.truststore.jks
    flat: yes

- name: fetch client truststore to local machine
  fetch: 
    src: "{{ truststore_client_path }}"
    dest: kafka-client.truststore.jks
    flat: yes
