- name: create zookeeper data directories
  file:
    path: "{{ zookeeper.config.dataDir }}"
    state: directory
    mode: 0755

- name: zookeeper stop script
  template:
    src: "zookeeper-stop.sh.j2"
    dest: "{{ confluent_bin_dir }}/zookeeper-stop.sh"
    mode: 0750

- name: zookeeper start script
  template:
    src: "zookeeper-start.sh.j2"
    dest: "{{ confluent_bin_dir }}/zookeeper-start.sh"
    mode: 0750

- name: zookeeper myid file
  template:
    src: myid.j2
    dest: "{{ zookeeper.config.dataDir }}/myid"
    mode: 0555

- name: zookeeper create config
  template:
    src: "zookeeper.properties.j2"
    dest: "{{ confluent_config_dir}}/{{ zookeeper.config_file }}"
    mode: 0400

- name: zookeeper jaas create config
  template:
    src: "zookeeper_jaas.conf.j2"
    dest: "{{ zookeeper_server_jaas}}"
    mode: 0400
  notify:
    - stop zookeeper
    - start zookeeper